---
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
  - vendor/**/*
  - test/**/*
  TargetRubyVersion: 2.5
Metrics/AbcSize:
  Max: 29
Layout/LineLength:
  Max: 100
  Include:
    - spec/**/*.rb
Metrics/MethodLength:
  Max: 40
Style/Documentation:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Style/NumericLiterals:
  MinDigits: 10
Layout/SpaceAroundOperators:
  Exclude:
    - attributes/default.rb
Layout/ExtraSpacing:
  AllowForAlignment: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
