---
name: "Tests"

env:
  cinc_workstation_version: 23

on:
  push:
    branches:
      - '*'

jobs:
  cookstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            .cache
          key: ${{ runner.os }}-${{ env.cinc_workstation_version }}
      - name: setup environment
        run: |
          mkdir -p .cache
          curl -L https://omnitruck.cinc.sh/install.sh | sudo bash -s -- -P cinc-workstation -d .cache -v ${{ env.cinc_workstation_version }}
      - name: cookstyle
        run: |
          cinc exec rake cookstyle

  kitchen-dokken:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cinc_version: [ '17', '18' ]
        kitchen_distro:
          - amazonlinux-1
          - amazonlinux-2
          - centos-7
          - centos-8
          - oracle-7
          - debian-9
          - debian-10
          - fedora-28
          - fedora-29
#          - opensuse-42 # something is broken here
          - ubuntu-16-04
          - ubuntu-18-04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            .cache
          key: ${{ runner.os }}-${{ env.cinc_workstation_version }}
      - name: setup environment
        run: |
          mkdir -p .cache
          curl -L https://omnitruck.cinc.sh/install.sh | sudo bash -s -- -P cinc-workstation -d .cache -v ${{ env.cinc_workstation_version }}
      - name: kitchen
        env:
          CINC_VERSION: ${{ matrix.cinc_version }}
          KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
        run: |
          kitchen test --color --destroy=always ${{ matrix.kitchen_distro }}
